[package]
name = "meddler"
version = "0.1.0"
edition = "2021"

[dependencies]
willhook = { version = "^0.6.3", features = ["serde"] }
serde_json = "1.0"
windows-service = "0.6.0"
once_cell = "1.17.0"

[[bin]]
name = "meddler"
